//! Typed toast variants and GPUI renderer for Tolaria (ADR-0115 Phase 2b).
//!
//! Phase 2c will swap `workspace::ToastLayer` from `Vec<SharedString>` to
//! `Vec<Toast>` and call [`render_toast`] from this crate.
//!
//! # Design notes
//!
//! [`ToastId`]s are generated by a global [`AtomicU64`](std::sync::atomic::AtomicU64)
//! counter rather than wall-time, so two toasts created in the same
//! microsecond still receive distinct, monotonically-increasing identifiers.
//!
//! [`render_toast`] constructs a GPUI element tree. Phase 2c will upgrade this
//! to a proper `Notification` view hosted in a `ToastLayer` entity.

use std::sync::{
    atomic::{AtomicU64, Ordering},
    Arc,
};
use std::time::Duration;

use gpui::{
    prelude::FluentBuilder as _, AnyElement, App, IntoElement as _, ParentElement as _,
    SharedString,
};
use gpui_component::notification::NotificationType;

// ---------------------------------------------------------------------------
// ToastId
// ---------------------------------------------------------------------------

static NEXT_ID: AtomicU64 = AtomicU64::new(0);

/// Opaque, monotonically-increasing toast identifier.
///
/// Values are drawn from a global [`AtomicU64`](std::sync::atomic::AtomicU64)
/// counter; see the crate-level docs for why this is preferred over wall-time.
///
/// The inner `u64` is private — callers must not fabricate or collide IDs.
/// Use [`PartialOrd`]/[`Ord`] impls for ordering comparisons.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ToastId(u64);

impl ToastId {
    fn next() -> Self {
        // Relaxed ordering is correct: no happens-before relationship is
        // required between ID issuance and any other memory access — each
        // fetch_add produces a unique value, which Relaxed guarantees.
        Self(NEXT_ID.fetch_add(1, Ordering::Relaxed))
    }
}

// ---------------------------------------------------------------------------
// ToastSeverity
// ---------------------------------------------------------------------------

/// Display severity of a [`Toast`].
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToastSeverity {
    Info,
    Success,
    Warning,
    Error,
}

impl From<ToastSeverity> for NotificationType {
    fn from(severity: ToastSeverity) -> Self {
        match severity {
            ToastSeverity::Info => NotificationType::Info,
            ToastSeverity::Success => NotificationType::Success,
            ToastSeverity::Warning => NotificationType::Warning,
            ToastSeverity::Error => NotificationType::Error,
        }
    }
}

// ---------------------------------------------------------------------------
// Toast
// ---------------------------------------------------------------------------

/// Reference-counted click handler invoked when the user activates a toast.
///
/// Pulled out into a named alias so the closure-shaped `Arc<dyn Fn(...)>`
/// type doesn't leak through Toast's stored field and accessor signatures
/// (clippy::type_complexity).  Bound `Send + Sync` so background tasks can
/// drop a toast (and indirectly drop the `Arc`) without the auto-traits
/// becoming a compile error at the wrong layer.
pub type ToastClickHandler = Arc<dyn Fn(&mut App) + Send + Sync + 'static>;

/// A single ephemeral toast notification.
///
/// Construct via [`Toast::info`], [`Toast::success`], [`Toast::warning`], or
/// [`Toast::error`]. Chain [`Toast::with_title`] to attach an optional title,
/// and [`Toast::on_click`] to register a callback fired when the user clicks.
///
/// Fields are private to preserve constructor invariants (e.g. monotonic IDs).
/// Access values through the provided accessor methods.  Also `#[non_exhaustive]`
/// so future fields don't require a SemVer-breaking constructor update at
/// every call-site.
#[non_exhaustive]
pub struct Toast {
    id: ToastId,
    severity: ToastSeverity,
    title: Option<SharedString>,
    message: SharedString,
    /// Optional action invoked (and the toast dismissed) when the user clicks.
    on_click: Option<ToastClickHandler>,
}

impl Toast {
    fn new(severity: ToastSeverity, message: impl Into<SharedString>) -> Self {
        Self {
            id: ToastId::next(),
            severity,
            title: None,
            message: message.into(),
            on_click: None,
        }
    }

    /// Create an informational toast.
    pub fn info(message: impl Into<SharedString>) -> Self {
        Self::new(ToastSeverity::Info, message)
    }

    /// Create a success toast.
    pub fn success(message: impl Into<SharedString>) -> Self {
        Self::new(ToastSeverity::Success, message)
    }

    /// Create a warning toast.
    pub fn warning(message: impl Into<SharedString>) -> Self {
        Self::new(ToastSeverity::Warning, message)
    }

    /// Create an error toast.
    pub fn error(message: impl Into<SharedString>) -> Self {
        Self::new(ToastSeverity::Error, message)
    }

    /// Attach an optional title to this toast (builder-style).
    pub fn with_title(mut self, title: impl Into<SharedString>) -> Self {
        self.title = Some(title.into());
        self
    }

    /// Register a click handler.  When the user clicks this toast the callback
    /// is invoked and the toast is dismissed.
    pub fn on_click(mut self, f: impl Fn(&mut App) + Send + Sync + 'static) -> Self {
        self.on_click = Some(Arc::new(f));
        self
    }

    /// How long this toast should remain visible before auto-dismissing.
    ///
    /// | Severity | Duration |
    /// |----------|----------|
    /// | Info / Success | 5 s |
    /// | Warning        | 8 s |
    /// | Error          | 10 s |
    pub fn auto_dismiss_duration(&self) -> Duration {
        match self.severity {
            ToastSeverity::Info | ToastSeverity::Success => Duration::from_secs(5),
            ToastSeverity::Warning => Duration::from_secs(8),
            ToastSeverity::Error => Duration::from_secs(10),
        }
    }

    /// The unique identifier for this toast.
    pub fn id(&self) -> ToastId {
        self.id
    }

    /// The display severity.
    pub fn severity(&self) -> ToastSeverity {
        self.severity
    }

    /// The optional title, if one was attached via [`Toast::with_title`].
    pub fn title(&self) -> Option<&SharedString> {
        self.title.as_ref()
    }

    /// The body message.
    pub fn message(&self) -> &SharedString {
        &self.message
    }

    /// The optional click handler registered via [`Toast::on_click`].
    pub fn click_handler(&self) -> Option<&ToastClickHandler> {
        self.on_click.as_ref()
    }
}

// ---------------------------------------------------------------------------
// render_toast
// ---------------------------------------------------------------------------

/// Render a [`Toast`] as a GPUI element.
///
/// Severity is mapped to the matching
/// [`NotificationType`](gpui_component::notification::NotificationType) via
/// [`From`]. The element is assembled from plain GPUI `div` nodes.
///
/// # Note
///
/// This function must be called from within a GPUI render context (inside a
/// themed window). `gpui_component::notification::Notification` is a GPUI
/// *view* (it implements [`gpui::Render`]) and must be hosted inside an entity
/// to become an element; that wiring belongs to Phase 2c's `ToastLayer` update.
/// Until then this function returns a lightweight `div`-based equivalent whose
/// severity mapping is documented via the [`From<ToastSeverity>`] impl for
/// [`NotificationType`].
pub fn render_toast(toast: &Toast) -> AnyElement {
    gpui::div()
        .when_some(toast.title().cloned(), |this, title| {
            this.child(gpui::div().child(title))
        })
        .child(gpui::div().child(toast.message().clone()))
        .into_any_element()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Every severity constructor must produce a toast without panicking.
    #[test]
    fn severity_variants_all_constructible() {
        let _info = Toast::info("info message");
        let _success = Toast::success("success message");
        let _warning = Toast::warning("warning message");
        let _error = Toast::error("error message");
    }

    /// `with_title` must preserve the original message unchanged.
    #[test]
    fn with_title_preserves_message() {
        let toast = Toast::info("the message").with_title("My Title");
        assert_eq!(toast.message(), &SharedString::from("the message"));
        assert_eq!(toast.title(), Some(&SharedString::from("My Title")));
    }

    /// Toasts created in sequence must have strictly increasing ids.
    #[test]
    fn ids_are_monotonic() {
        let ids: Vec<ToastId> = (0..5).map(|_| Toast::info("x").id()).collect();
        assert!(
            ids.windows(2).all(|w| w[0] < w[1]),
            "toast ids must be strictly monotonic"
        );
    }

    /// `render_toast` must not panic when the theme is installed and a window
    /// is present.
    #[gpui::test]
    fn render_toast_no_panic(cx: &mut gpui::TestAppContext) {
        cx.update(gpui_component::init);

        struct Host(Toast);

        impl gpui::Render for Host {
            fn render(
                &mut self,
                _window: &mut gpui::Window,
                _cx: &mut gpui::Context<Self>,
            ) -> impl gpui::IntoElement {
                render_toast(&self.0)
            }
        }

        let toast = Toast::error("something went wrong");
        let _window = cx.add_window_view(|_window, _cx| Host(toast));
        cx.run_until_parked();
    }
}
